# Generated by Django 5.1.3 on 2024-12-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0002_sellerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
