# Generated by Django 5.1.3 on 2024-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0003_rename_age_sellerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
