# Generated by Django 5.1.3 on 2024-12-03 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0005_alter_sellerprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('facebook', models.URLField(null=True)),
                ('number', models.CharField(max_length=12)),
                ('skill', models.TextField(max_length=200)),
                ('has_profile', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
