# Generated by Django 5.1.3 on 2024-12-03 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0006_userprofile_delete_sellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +9779XXXXXXXX or 9XXXXXXXX.', regex='^\\+9779\\d{8}$|^9\\d{8}$')]),
        ),
    ]
