# Generated by Django 5.1.3 on 2024-12-04 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0007_remove_userprofile_is_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +9779XXXXXXXX or 9XXXXXXXX.', regex='^\\+9779\\d{8}$|^9\\d{8}$')]),
        ),
    ]
