# Generated by Django 5.1.3 on 2024-12-04 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0009_alter_userprofile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(help_text='Enter phone number in the format: +9779XXXXXXXX or 9XXXXXXXX.', max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +9779XXXXXXXX or 9XXXXXXXX.', regex='^\\+9779\\d{8}$|^9\\d{8}$')]),
        ),
    ]
