# Generated by Django 5.1.3 on 2024-12-05 10:47

import hirehub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0010_alter_userprofile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', validators=[hirehub.models.UserProfile.validate_image]),
        ),
    ]
