# Generated by Django 5.1.3 on 2024-12-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0011_userprofile_gender_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
