# Generated by Django 5.1.3 on 2024-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0014_alter_userprofile_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mechanic', 'Mechanic'), ('carpenter', 'Carpenter'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('housekeeper', 'House Kepper'), ('builder', 'Builder'), ('welders', 'Welders'), ('window-installer', 'Window Installer'), ('tile-setter', 'Tile Setter'), ('gardening-experts', 'Gardening Experts'), ('cleaner', 'Cleaner'), ('babysitter', 'Babysitter'), ('caterer', 'Caterer'), ('driver', 'Driver'), ('others', 'Others')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(to='hirehub.skill'),
        ),
    ]
