# Generated by Django 5.1.3 on 2024-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0015_skill_remove_userprofile_skill_userprofile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('carpenter', 'Carpenter'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('housekeeper', 'House Kepper'), ('builder', 'Builder'), ('welders', 'Welders'), ('window-installer', 'Window Installer'), ('tile-setter', 'Tile Setter'), ('gardening-experts', 'Gardening Experts'), ('cleaner', 'Cleaner'), ('babysitter', 'Babysitter'), ('caterer', 'Caterer'), ('driver', 'Driver'), ('others', 'Others')], max_length=50),
        ),
    ]
