# Generated by Django 5.1.3 on 2024-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0019_remove_userprofile_skills_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
