# Generated by Django 5.1.3 on 2025-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0021_skill_remove_userprofile_skills_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
