# Generated by Django 5.1.3 on 2025-01-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirehub', '0022_userprofile_is_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_buyer',
        ),
    ]
